version: '3'
 
services:
 
  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
       - ./code:/data/application.local
       - ./fpm/config/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - app-network
 
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    volumes:
       - ./code:/data/application.local
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: myapp/mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge